### DISCUSSION TITLE
Collection of custom tweaks

### DISCUSSION THREAD

**Discussion by lonix1** [be5invis/vscode-custom-css#197] [Ideas]
Is there a collection / gist / awesome list / whatever of people's customisations using this extension?

I'm sure many of us are customising vscode in the same way, so would be useful to pool such tweaks in a common place. Does such a collection exist?

**Comment by cloorc** [comment]
Let's start a new gist about this: https://gist.github.com/cloorc/d2882523def38ce1ca3752b09e4e8fb2

**Comment by trusktr** [comment]
This thread will be great for some notes. I also made a [CSS Themes](https://github.com/be5invis/vscode-custom-css/issues/183) thread where we can paste our themes.

<details open><summary>

## Tabs

</summary>

Styling tabs is rather annoying. After I installed Monokai Pro theme, here's what my tabs look like:

![Screen_Recording_2023-02-24_at_7_32_10_PM_AdobeExpress](https://user-images.githubusercontent.com/297678/221334079-c6355a46-1760-402e-955e-4135455c31f6.gif)

With this CSS:

```css
/**
TABS
*/

/* Make hovered non-active tabs' backgrounds get slightly lighter on hover. */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab:hover,
.monaco-workbench .part.editor > .content .editor-group-container.active > .title .tabs-container > .tab:hover {
    background-color: rgba(255, 255, 255, 0.04) !important;
}

.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab {
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
}

.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab:first-child {
    border-top-left-radius: 0;
}

/* Actually make the selected tab's background different than others. */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab.active {
    background-color: rgba(255, 255, 255, 0.06) !important;
}

/* Make hovered active tab's background get slightly lighter on hover. */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab.active:hover,
.monaco-workbench .part.editor > .content .editor-group-container.active > .title .tabs-container > .tab.active:hover {
    background-color: rgba(255, 255, 255, 0.1) !important;
}

/* Ensure that a selected Tab's bottom-border stays the same color when we hover
 * on it (it was going from yellow accent color to gray, super ugly).
 */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab.active.tab-border-bottom > .tab-border-bottom-container {
    /** We added "!important" (And we needed !important everywhere else too, what the heck) */
    background-color: var(--tab-border-bottom-color) !important;
}
```

</details>


<details><summary>

## Cursor

</summary>

The cursor can be found in a div with class `cursors-layer`, and the cursor itself has class `cursor`:

<img width="320" alt="Screenshot 2023-02-24 at 7 35 13 PM" src="https://user-images.githubusercontent.com/297678/221334151-794f4881-b5ba-492a-b516-ef5e51041aa5.png">

```css
.monaco-editor .cursors-layer .cursor {
    background-color: deeppink;
    border-color: deeppink;
}
```

If you're using VS Code Vim, you can style its fake cursors (f.e. the one used in VISUAL selection mode) like so:

<img width="357" alt="Screenshot 2023-02-24 at 7 36 49 PM" src="https://user-images.githubusercontent.com/297678/221334205-4f4cec1c-05fb-4c9e-99e9-d1dc305e5732.png">

```css
/** This highlights the fake cursors (f.e. on visual select) as well as the momentary highlight of yanked text. */
[class*="ced-1-TextEditorDecorationType"] {
    background-color: deeppink;
    border-color: deeppink;
}
```

VS Code uses a lot of `!important`. To override some things like color, you'll need to use a specific-enough selector, and `!important` as well:

```css
.vs-dark.monaco-editor [class*="ced-1-TextEditorDecorationType"] {
    color: white !important;
}
```

</details>

**Comment by wroyca** [comment]
https://github.com/wroyca/vscode-libadwaita

![libadwaita](https://user-images.githubusercontent.com/91024200/222934247-f9e5da58-9ed0-4940-8410-bf7b2dc23ae7.png)

**Comment by Krysl** [comment]
Move VSCode `debug toolbar` to `Activity Bar`

https://github.com/Krysl/vscode-move-debug-toolbar-to-activitybar

![screen recording](https://user-images.githubusercontent.com/5905801/232450757-84fdbbee-85f2-4cf0-9ef3-314433dd6012.png)

**Comment by BabcB** [comment]
ok @lonix1 , I will create it as separate issue

**Comment by distek** [comment]
Someone could probably write this better, but make terminal take up full width and height of panel's view:
``` css
.integrated-terminal.shell-integration .xterm, .monaco-workbench .pane-body.integrated-terminal .terminal-group .monaco-split-view2.horizontal .split-view-view:first-child .xterm, .monaco-workbench .terminal-editor .xterm{
  padding: 0 0 0 0 !important;
  margin: 0 0 0 0 !important;
}

.monaco-workbench .pane-body.integrated-terminal .xterm, .monaco-workbench .terminal-editor .xterm {
    bottom: 0;
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
}
```

![image](https://github.com/be5invis/vscode-custom-css/assets/49327592/c3611768-9e0a-4299-8806-f73d6c27b45a)

Drive me bananas to have that much wasted space.
