### ISSUE TITLE
command 'extension.installCustomCSS' not found

### ISSUE THREAD

**Issue by JacobMGEvans** [be5invis/vscode-custom-css#131]
When attempting to Enable Custom CSS and JS 
This is likely something related to my `beta` environment. Figured it might help get ahead of a possible future issue.
System: 
```yaml
Version: 1.52.0-insider
Commit: a36c68b9ec3d6a0aca9799d7a10be741a6658a51
Date: 2020-11-19T05:38:14.978Z (23 hrs ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```
