### ISSUE TITLE
Extension loads and does nothing

### ISSUE THREAD

**Issue by apaz-cli** [be5invis/vscode-custom-css#138]
```
code --version
1.54.1
f30a9b73e8ffc278e71575118b6bf568f04587c8
x64
```

```json
/**settings.json*/
    "vscode_custom_css.staging_dir": "file:///home/apaz/.vscode/extensions/be5invis.vscode-custom-css-5.0.2/staging_dir/",
    "vscode_custom_css.imports": [
        "file:///home/apaz/.vscode/extensions/be5invis.vscode-custom-css-5.0.2/staging_dir/vscode_style.css"
    ],
    "vscode_custom_css.policy": true,
 ```

I created the directory and the file. When it can't find vscode_style.css the extension yells at me, so I figure that it finding the file must not be the issue. I've also chowned /usr/share/code and all of .vscode, so permissions shouldn't be an issue. Everything seems to go right, but the css is not applied. The extension host log prints no relevant messages either. 

It likely doesn't matter, but here's the content of that css file.
```css
/**vscode_style.css*/
body{
   pointer-events: auto !important;
   background-size: 100% !important;
   opacity: 0.97 !important;
   background-position: 0 0 !important;
   /* The file is present here also. */
   background-image: url('file:///home/apaz/Pictures/Icons-Resources/VSCode_BG.jpg');
   content: '';
   position: absolute;;
   z-index: 999;
   width: 100%;
   background-repeat: no-repeat;
}
```

With my old configuration broken, and now the new one broken, I'm not quite sure how to use the extension correctly anymore. Perhaps the readme could be updated. There's some outdated information on it.
