### ISSUE TITLE
VS Code Custom CSS Themes!

### ISSUE THREAD

**Issue by trusktr** [be5invis/vscode-custom-css#183]
Let's share our themes here.

**Comment by trusktr** [comment]
This one is Monokai Pro (paid) theme, plus my customizations for the smooth tab animation and the hot pink glowing CSS cursor (and VS Code Vim yank highlight):


https://user-images.githubusercontent.com/297678/221334927-470ea2d9-8b42-403a-9df5-a2e426a9fccd.mov

<br />

<details>
<summary>
Here's the CSS (click to expand):
</summary>

```css
/**
TABS
*/

/** tabs background and inactive tab have same color */
.tabs-and-actions-container {
    background: rgba(0, 0, 0, 0.2);
}
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab,
.monaco-workbench .part.editor > .content .editor-group-container.active > .title .tabs-container > .tab {
    background-color: rgba(255, 255, 255, 0) !important;
    border-right: none !important;
    transition: all 150ms;
}

/* Make hovered non-active tabs' backgrounds get slightly lighter on hover (thank god). */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab:hover,
.monaco-workbench .part.editor > .content .editor-group-container.active > .title .tabs-container > .tab:hover {
    background-color: rgba(255, 255, 255, 0.04) !important;
}

.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab {
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
}

.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab:first-child {
    border-top-left-radius: 0;
}

/* Actually make the selected tab's background different than others (thank god). */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab.active {
    background-color: rgba(255, 255, 255, 0.06) !important;
}

/* Make hovered active tab's background get slightly lighter on hover (thank god). */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab.active:hover,
.monaco-workbench .part.editor > .content .editor-group-container.active > .title .tabs-container > .tab.active:hover {
    background-color: rgba(255, 255, 255, 0.1) !important;
}

/* Ensure that a selected Tab's bottom-border stays the same color when we hover
 * on it (it was going from yellow accent color to gray, ugly as heck).
 */
.monaco-workbench .part.editor > .content .editor-group-container > .title .tabs-container > .tab.active.tab-border-bottom > .tab-border-bottom-container {
    /** We added "!important" (And we needed !important everywhere else too, what the hell) */
    background-color: var(--tab-border-bottom-color) !important;
}

/**
CURSOR
*/

.monaco-editor .cursors-layer .cursor {
    color: white;
    background-color: deeppink;
    border-color: deeppink;
    box-shadow: 0 0 7px deeppink;
}

/** This highlights the fake cursors (f.e. on visual select) as well as the momentary highlight of yanked text. */
.vs-dark.monaco-editor [class*="ced-1-TextEditorDecorationType"] {
    color: white !important;
    background-color: deeppink;
    border-color: deeppink;
    box-shadow: 0 0 7px deeppink;
}

```

</details>
