### ISSUE TITLE
Windows. CSS Font Family doesn't work

### ISSUE THREAD

**Issue by artemKerimoff** [be5invis/vscode-custom-css#238]
Customising the Explorer panel in VS Code. I have set the following style for it:
```css
/* File Explorer Item Label */
.monaco-tree .monaco-tree-row .label-name,
.monaco-list .monaco-list-row
.monaco-icon-label .label-name,
.monaco-highlighted-label {
    font-family: 'Geist Mono', monospace !important;
    font-size: 14px !important;
    font-weight: 400 !important;
    color: #FFF !important;
}
```
however, even when I run the ‘enable custom css and js’ command, it's as if the Geist Mono font is not visible and the default font with monospace is set.
this is how the explorer panel looks like after running the command:
![image](https://github.com/user-attachments/assets/d45e2ed0-a989-4e50-b658-2e9ce729e17f)
and it should look like this (we are talking about the font):
![image](https://github.com/user-attachments/assets/df053c66-5e82-4936-a822-0c5bfec392c5)
