### ISSUE TITLE
Problem with window style

### ISSUE THREAD

**Issue by MaxZhirniy** [be5invis/vscode-custom-css#244]
* VSCodium 1.94.2 
* Windows 10
Hi. Im trying to change watermark on Welcome page and change window icon with this code:
```css
.monaco-workbench .part.titlebar .window-appicon > .home-bar-icon-badge,
.monaco-workbench .part.titlebar > .window-appicon:not(.codicon) {
    background-image: url("code.png") !important;
    background-repeat: no-repeat;
    background-position: 50%;
}
.editor-group-watermark>.letterpress {
    background-image:url("code.svg") !important;
    opacity: 0.75;
    overflow: visible;
    filter: none;
    transform: scale(1.5, 1.5);
}
```
watermark replaced to black (welcome dont have watermark, window icon without changes)
