### ISSUE TITLE
border-radius not work

### ISSUE THREAD

**Issue by pandacase** [be5invis/vscode-custom-css#255]
```css
/**
WORD HIGHLIGHT
*/

@keyframes rainbow-flow {
  0% { border-image-source: linear-gradient(0deg, rgb(227, 188, 188), rgb(224, 206, 172), rgb(215, 215, 194), rgb(176, 223, 176), rgb(172, 235, 235), rgb(160, 160, 236), rgb(255, 182, 255)); }
  25% { border-image-source: linear-gradient(90deg, rgb(255, 182, 255), rgb(227, 188, 188), rgb(224, 206, 172), rgb(215, 215, 194), rgb(176, 223, 176), rgb(172, 235, 235), rgb(160, 160, 236)); }
  50% { border-image-source: linear-gradient(180deg, rgb(160, 160, 236), rgb(255, 182, 255), rgb(227, 188, 188), rgb(224, 206, 172), rgb(215, 215, 194), rgb(176, 223, 176), rgb(172, 235, 235)); }
  75% { border-image-source: linear-gradient(270deg, rgb(172, 235, 235), rgb(160, 160, 236), rgb(255, 182, 255), rgb(227, 188, 188), rgb(224, 206, 172), rgb(215, 215, 194), rgb(176, 223, 176)); }
  100% { border-image-source: linear-gradient(360deg, rgb(227, 188, 188), rgb(224, 206, 172), rgb(215, 215, 194), rgb(176, 223, 176), rgb(172, 235, 235), rgb(160, 160, 236), rgb(255, 182, 255)); }
}

.monaco-editor .wordHighlight,
.monaco-editor .wordHighlightStrong {
  border: 2px solid;
  border-image-slice: 1;
  border-radius: 2px !important;
  padding: 2px !important;
  animation: rainbow-flow 12s linear infinite;
}
```

border-radius & padding for word highlight not work, how to fix it. 😭

![Image](https://github.com/user-attachments/assets/c4272e12-1383-4bc3-9fa8-f827c3ee33c0)
