### ISSUE TITLE
Styles not applied on Windows 7 VsCode version 1.20.1

### ISSUE THREAD

**Issue by dsych** [be5invis/vscode-custom-css#34]
Here is the URL sample that I use to navigate to the css file:
"vscode_custom_css.imports": ["file:///Users/user.name/vscode_styles/styles.css"]
I have started the extension and able to see the bucket in the status bar. Devtools console outputs:
[Extension Host] vscode-customcss is active!
Here is a sample class:
```css
 .mtk11 {
    font-family: 'Script12 BT';
    font-style: normal;
  }
```
