### ISSUE TITLE
Not working, Windows 10

### ISSUE THREAD

**Issue by ashrafhadden** [be5invis/vscode-custom-css#60]
#### VSCode About
Version: 1.30.0 (system setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
#### About your PC
Windows 10 Home Single Language v. 1803 (OS Build 17134.471)

I've tried disabling all other extensions, running in Admin, moving the CSS file to Documents and many other directories and even reinstalling extension. The symbol on the status bar shows that it's working but nothing is being affected by my CSS. The only other thing I can think of is perhaps permissions which you mention solutions for Mac and Linux but not Windows.

If you have a full-proof example CSS file I could use for testing that would be great. Although I've used this same one successfully on my mac and have messed around even using the built-in devtools `Copy selector` to make sure it isn't my faulty selection path but to no avail.

CSS i'm using...
```css
/* /// Global VSCode Font */
body {
  font-family: 'Arial', sans-serif !important;
  /* font-family: 'Roboto', sans-serif !important; */
  /* font-family: 'Open Sans', sans-serif !important; */
  /* font-family: 'K2D', sans-serif !important; */
  /* font-family: 'Noto Sans', sans-serif !important; */
}

#workbench\2e parts\2e sidebar > div.composite.title > div.title-label > h2 {
  display: none !important;
}

#workbench\2e parts\2e statusbar > div:nth-child(5) > div > a.editor-status-eol {
  display: none !important;
}

[aria-label='Editor actions'] {
  display: none !important;
}
```
