### ISSUE TITLE
Custom CSS Not working anymore.

### ISSUE THREAD

**Issue by kevindrc** [be5invis/vscode-custom-css#67]
After VS Code insiders New version update Custom CSS stopped working, have tried with Administrator and enable and restated many times, but still not working.

**Comment by kevindrc** [comment]
Found fixes, font-family now not working anymore without the !important style, applied !important to every styles and it works !.

**Comment by ashrafhadden** [comment]
Seems broken again in Insiders v1.32.0 but only for certain selectors like `body`.

```css
/* gets overrided */
body {
  font-family: Ubuntu !important;
}

/* works */
[aria-label='Editor actions'] {
  display: none !important;
}

/* works */
.editor-status-eol {
  display: none !important;
}
```
