### ISSUE TITLE
How to remove github branch

### ISSUE THREAD

**Issue by brianabaker** [be5invis/vscode-custom-css#70]
Hello, I'd love to remove the github branch from the status bar. Does anyone know how to target it so I can remove it? I opened up `workbench.main.css` in my VSCode directory but I didn't find it. Thank you!

**Comment by usernamehw** [comment]
@brianabaker this code will target 2 icons: git branch & git synchronize 🔄:

```css
[statusbar-entry-alignment="0"][statusbar-entry-priority="10000"] {
    display: none !important;
}
```

Or you can target it more granular:

```css
.statusbar-item > a[title$='Checkout...'] {
    display: none !important;
}
```

You can use **Developer: Toggle Developer Tools** to find needed scopes:
![demo](https://user-images.githubusercontent.com/9638156/54013709-38294880-418b-11e9-8a9d-939ef2a8d9f5.gif)
